#!/bin/bash
function get_file() {
        if [ `echo $1 | grep "http://" -` ] || [ `echo $1 | grep "https://" -` ] || [ `echo $1 | grep "ftp://" -` ] ; then
                export TSUN_PACKNAME=$(basename "$1")
                export TSUN_EXT=${TSUN_PACKNAME#*.}
                export TSUN_PKG=$(remove_ext "$TSUN_PACKNAME")
	        export TSUN_NAME=$(echo $(echo $TSUN_PKG | sed 's/-.*//g') | sed 's/[0123456789\.]//g')
	        export TSUN_VER=$(echo $TSUN_PKG | sed "s/$TSUN_NAME-//g")
                cd $TSUNDIR/$tsun_f
                fetch_wget $1
        elif [ `echo $1 | grep "git://" -` ]; then
		cd $TSUNDIR/$tsun_f
                git clone $1 || fail
        else
                fetch_copy $1
        fi
}
