#!/bin/bash
function remove_ext() {
	echo $(echo $1 | \
		sed 's/\.tgz//' | \
		sed 's/\.txz//' | \
		sed 's/\.tbz2//' | \
		sed 's/\.gz//' | \
		sed 's/\.xz//' | \
		sed 's/\.bz2//' | \
		sed 's/\.zip//' | \
		sed 's/\.tar//' #| \
	)
}
