#!/bin/bash

#######################################################
#                                                     #
#  THIS IS A TEMPLATE FILE FOR MAKING NEW SCRIPTS     #
#  IT SERVES ONLY AS AN EXAMPLE, NOTHING MORE.        #
#                                                     #
#######################################################

function build() {
	export LUA51_LIBS='-llua -lm'

	_loge "Configuring..."
        _configure --prefix=$TSUN_PREFIX --libdir=$TSUN_LIBDIR --sysconfdir=/etc --enable-shared --with-pic=yes --enable-lua --enable-imlib2 --enable-lua-imlib2 --enable-lua-cairo

	_loge "Building..."
	_make

	_loge "Installing..."
	_make install
}
