#!/bin/bash
function build() {
	# System software. Yes, '/'. We install to the root.
	_loge "Configuring (for /)..."
	_configure --with-xz --with-zlib --prefix=/

	_loge "Building..."
	_make

	_loge "Installing..."
	_make install
}
