#!/bin/bash
function build() {
	_loge "Configuring..."
	_log ./config --prefix=/usr --openssldir=/etc/ssl --libdir=$TSUN_LIBDIR shared zlib-dynamic

	_loge "Building..."
	_make

	_loge "Installing..."
	_make install
}
